language: scala

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk8

dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

deploy:
  - provider: releases
    file:
      - xtract-core/target/**/*.jar
      - testing/target/**/*.jar
    file_glob: true
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      repo: lucidsoftware/xtract
  - provider: script
    script: bash publish.sh
    skip_cleanup: true
    on:
      repo: lucidsoftware/xtract

before_script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile packageBin packageDoc packageSrc
  - sbt ++$TRAVIS_SCALA_VERSION test

install: sbt ++$TRAVIS_SCALA_VERSION update
before_cache:
  #Avoid unncessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
